apiVersion: v1
kind: Service
metadata:
  name: posecloud-service
spec:
  selector:
    app: posecloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
